#!/usr/bin/env python3
# Usage: python3 pipeline/make_figures.py   # regenerates docs/figures/*.png,*.svg
"""
Render the headline aggregate figures for the README, from committed aggregate
caches only. NO network, NO SEC calls, NO issuer-level data — it reads only the
per-year aggregate CSVs under data/aggregates/ (which the pre-commit gate,
scripts/check_public_safe.py, verifies are issuer-free).

Inputs (all aggregate, one row per year / per year-sector):
  data/aggregates/ai_prevalence.csv     year, pct_artificial_intelligence, pct_generative_ai, ...
  data/aggregates/ai_buckets_by_year.csv year, B_marketing, C_substance, A_core, ...  (% of filers)
  data/aggregates/ai_sector_by_year.csv  year, sic2, pct_of_ai_filings, ...            (long form)

Outputs (committed, embedded in the README):
  docs/figures/f1_adoption.{png,svg}     the label went everywhere
  docs/figures/f2_marketing_vs_substance.{png,svg}   ...but the substance did not follow
  docs/figures/f3_sector_diffusion.{png,svg}         ...and it left software

Reproducible: matplotlib is pinned in requirements.txt; output is stable across
runs (fixed backend/font, suppressed timestamps). Reproducibility is "renders
without error and matches the committed numbers," not a byte-identical diff.
"""
import csv
import os
import sys

import matplotlib
matplotlib.use("Agg")  # headless, deterministic backend
import matplotlib.pyplot as plt

# Deterministic-ish output: stable SVG element ids, matplotlib's always-present
# default font, no interactive state.
matplotlib.rcParams["svg.hashsalt"] = "ai-disclosure-measurement"
matplotlib.rcParams["font.family"] = "DejaVu Sans"
matplotlib.rcParams["figure.dpi"] = 120
matplotlib.rcParams["axes.spines.top"] = False
matplotlib.rcParams["axes.spines.right"] = False

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
AGG = os.path.join(ROOT, "data", "aggregates")
OUT = os.path.join(ROOT, "docs", "figures")

INK = "#1a1a1a"
MUTED = "#8a8a8a"
ADOPT = "#0b6e99"    # adoption / core
MARKET = "#c1440e"   # marketing (hot)
SUBST = "#2f7d4f"    # substance (cool)
GRID = "#e6e6e6"
SOURCE = "Source: SEC EDGAR full-text search + full-index (public). Regenerated by pipeline/make_figures.py."


def _read(name):
    path = os.path.join(AGG, name)
    if not os.path.isfile(path):
        sys.exit(
            "missing aggregate: %s\n"
            "Generate it offline (see pipeline/) and copy it into data/aggregates/."
            % os.path.relpath(path, ROOT)
        )
    with open(path, newline="", encoding="utf-8") as fh:
        return list(csv.DictReader(fh))


def _style(ax, title, subtitle, ylabel):
    ax.set_title(subtitle, fontsize=11, color=MUTED, loc="left", pad=6)
    ax.text(0.0, 1.10, title, transform=ax.transAxes, fontsize=15,
            fontweight="bold", color=INK, va="bottom")
    ax.set_ylabel(ylabel, fontsize=10, color=INK)
    ax.grid(axis="y", color=GRID, linewidth=0.8)
    ax.tick_params(colors=INK, labelsize=9)
    ax.set_axisbelow(True)


def _save(fig, stem, source=SOURCE):
    os.makedirs(OUT, exist_ok=True)
    fig.text(0.01, 0.005, source, fontsize=6.5, color=MUTED, ha="left", va="bottom")
    for ext in ("png", "svg"):
        fig.savefig(os.path.join(OUT, f"{stem}.{ext}"),
                    bbox_inches="tight", metadata={"Date": None} if ext == "svg" else {})
    plt.close(fig)
    print(f"[fig] docs/figures/{stem}.png / .svg")


def fig1_adoption(prev):
    yrs = [int(r["year"]) for r in prev]
    ai = [float(r["pct_artificial_intelligence"]) for r in prev]
    gen = [float(r.get("pct_generative_ai", 0) or 0) for r in prev]
    fig, ax = plt.subplots(figsize=(8, 4.6))
    ax.plot(yrs, ai, color=ADOPT, linewidth=2.6, label='"artificial intelligence"')
    ax.plot(yrs, gen, color=MARKET, linewidth=1.8, linestyle="--", label='"generative AI"')
    ax.fill_between(yrs, ai, color=ADOPT, alpha=0.06)
    ax.set_ylim(0, max(ai) * 1.12)
    ax.annotate(f"{ai[0]:.1f}%  ({yrs[0]})", (yrs[0], ai[0]), textcoords="offset points",
                xytext=(6, 8), fontsize=9, color=INK)
    ax.annotate(f"{ai[-1]:.0f}%  ({yrs[-1]})", (yrs[-1], ai[-1]), textcoords="offset points",
                xytext=(-52, -4), fontsize=9, color=INK, fontweight="bold")
    ax.legend(frameon=False, fontsize=9, loc="upper left")
    _style(ax, "The AI label went everywhere",
           'Share of 10-K filers mentioning the phrase, %s–%s' % (yrs[0], yrs[-1]),
           "% of 10-K filers")
    _save(fig, "f1_adoption")


def fig2_marketing_vs_substance(buckets):
    yrs = [int(r["year"]) for r in buckets]
    mkt = [float(r["B_marketing"]) for r in buckets]
    sub = [float(r["C_substance"]) for r in buckets]
    fig, ax = plt.subplots(figsize=(8, 4.6))
    ax.plot(yrs, mkt, color=MARKET, linewidth=2.6, label="Marketing vocabulary  (AI-powered, AI-driven)")
    ax.plot(yrs, sub, color=SUBST, linewidth=2.6, label="Build vocabulary  (LLM, training compute, fine-tuning)")
    ax.fill_between(yrs, mkt, sub, where=[m >= s for m, s in zip(mkt, sub)],
                    color=MARKET, alpha=0.07)
    ax.set_ylim(0, max(mkt) * 1.2)
    ax.annotate(f"{mkt[-1]:.1f}%", (yrs[-1], mkt[-1]), textcoords="offset points",
                xytext=(-38, 4), fontsize=9, color=MARKET, fontweight="bold")
    ax.annotate(f"{sub[-1]:.1f}%", (yrs[-1], sub[-1]), textcoords="offset points",
                xytext=(-30, -12), fontsize=9, color=SUBST, fontweight="bold")
    ax.legend(frameon=False, fontsize=9, loc="upper left")
    _style(ax, "...but the substance did not follow",
           "Cheap marketing language spread; costly build language stayed pinned near zero",
           "% of 10-K filers")
    _save(fig, "f2_marketing_vs_substance")


def fig3_sector_diffusion(sector):
    # SIC-73 (business & IT services / software) share of AI-mention volume, per year.
    share = {}
    for r in sector:
        if str(r["sic2"]).zfill(2) == "73":
            share[int(r["year"])] = float(r["pct_of_ai_filings"])
    yrs = sorted(share)
    vals = [share[y] for y in yrs]
    peak_y = max(yrs, key=lambda y: share[y])
    peak_v = share[peak_y]
    fig, ax = plt.subplots(figsize=(8, 4.6))
    ax.plot(yrs, vals, color=ADOPT, linewidth=2.6)
    ax.fill_between(yrs, vals, color=ADOPT, alpha=0.06)
    ax.set_ylim(0, peak_v * 1.18)
    # Honest annotation: the series rises (noisy, small early samples) and then
    # falls from its ~2018 peak. Mark the peak and the latest year, not 2001.
    ax.annotate(f"peak {peak_v:.0f}% ({peak_y})", (peak_y, peak_v),
                textcoords="offset points", xytext=(-20, 8), fontsize=9,
                color=INK, fontweight="bold")
    ax.annotate(f"{vals[-1]:.0f}% ({yrs[-1]})", (yrs[-1], vals[-1]),
                textcoords="offset points", xytext=(-30, -14), fontsize=9,
                color=INK, fontweight="bold")
    _style(ax, "...and it spread beyond software",
           "Software's (SIC-73) share of all AI mentions: after its ~%s peak, the label diffuses into every sector" % peak_y,
           "SIC-73 share of AI mentions, %")
    _save(fig, "f3_sector_diffusion")


def fig4_informativeness(info):
    # Disciplining null (the "lemons" precondition): as the AI label proliferated,
    # did AI-labeled filers still look like real R&D firms? Two panels — pool
    # quality (share reporting any R&D) and the R&D-intensity premium vs the
    # market. Only 4 benchmark years; 2015 is a small sample (few AI filers), so
    # it is drawn faded and flagged.
    yrs = [int(r["year"]) for r in info]
    nfirms = [int(r["ai_firms"]) for r in info]
    pct = [float(r["pct_ai_reporting_rnd"]) for r in info]
    prem = [float(r["substance_premium"]) for r in info]
    small = [n < 100 for n in nfirms]  # flag small-sample years (2015)
    x = list(range(len(yrs)))
    labels = [f"{y}\n(n={n})" for y, n in zip(yrs, nfirms)]

    fig, (axA, axB) = plt.subplots(1, 2, figsize=(9.4, 4.5))

    # Panel A: share reporting any R&D
    barsA = axA.bar(x, pct, color=[MUTED if s else ADOPT for s in small], width=0.62)
    for xi, v in zip(x, pct):
        axA.text(xi, v + 1, f"{v:.0f}%", ha="center", fontsize=9, color=INK)
    axA.set_ylim(0, max(pct) * 1.2)
    axA.set_title("Share reporting any R&D", fontsize=10.5, color=INK, loc="left")
    axA.set_ylabel("% of AI-labeled filers", fontsize=9, color=INK)

    # Panel B: R&D-intensity premium over the market baseline, with 95% bootstrap CIs.
    lo = [float(r["premium_ci_lo"]) for r in info]
    hi = [float(r["premium_ci_hi"]) for r in info]
    colors = [MUTED if s else (SUBST if v >= 0 else MARKET) for s, v in zip(small, prem)]
    axB.bar(x, prem, color=colors, width=0.62)
    axB.axhline(0, color=INK, linewidth=0.9)
    yerr = [[p - l for p, l in zip(prem, lo)], [h - p for h, p in zip(hi, prem)]]
    axB.errorbar(x, prem, yerr=yerr, fmt="none", ecolor=INK, elinewidth=1.1, capsize=4)
    # Fixed, readable window; the 2015 small-sample CI runs far off-scale and is annotated.
    axB.set_ylim(-0.16, 0.09)
    for xi, v, s in zip(x, prem, small):
        axB.text(xi, -0.15, f"{v:+.3f}", ha="center", va="bottom", fontsize=8.5,
                 color=MUTED if s else INK)
    for xi, s, h in zip(x, small, hi):
        if h > 0.09:  # CI whisker off the top (2015)
            axB.annotate("CI to\n+%.1f" % h, (xi, 0.085), ha="center", va="top",
                         fontsize=7.5, color=MUTED)
    # Overlay the size-adjusted premium (assets terciles) as points; its wider CIs are
    # reported in the text, not drawn, to keep the axis readable.
    def _num(v):
        try: return float(v)
        except (TypeError, ValueError): return None
    sa = [(xi, _num(r.get("premium_size_adj"))) for xi, r in zip(x, info)]
    sa = [(xi, v) for xi, v in sa if v is not None]
    if sa:
        axB.plot([p[0] for p in sa], [p[1] for p in sa], marker="D", ms=6, color=ADOPT,
                 lw=1.2, ls="--", label="size-adjusted", zorder=5)
        axB.legend(frameon=False, fontsize=8, loc="upper right")
    axB.set_title("R&D-intensity premium vs. market (95% CI)", fontsize=10.5, color=INK, loc="left")
    axB.set_ylabel("median R&D/revenue, AI minus baseline", fontsize=9, color=INK)

    for ax in (axA, axB):
        ax.set_xticks(x)
        ax.set_xticklabels(labels, fontsize=8.5)
        ax.grid(axis="y", color=GRID, linewidth=0.8)
        ax.set_axisbelow(True)
        ax.tick_params(colors=INK, labelsize=9)

    fig.subplots_adjust(top=0.74, wspace=0.30)
    fig.text(0.02, 0.98, "The label's link to real capability faded", fontsize=15,
             fontweight="bold", color=INK, va="top", transform=fig.transFigure)
    fig.text(0.02, 0.90, "Audited R&D among AI-labeled 10-K filers as the label spread from 37 to ~2,400 firms "
             "(2015 faded: small sample)", fontsize=9.5, color=MUTED, va="top", transform=fig.transFigure)
    _save(fig, "f4_informativeness")


def fig5_placebo(placebo):
    # Placebo: apply the SAME "<term>-powered / <term>-driven" marketing template to AI and
    # to control buzzwords. Only AI produces a large marketing vocabulary; the controls stay
    # near zero. That is the decoupling being specific to AI, not a generic buzzword effect.
    terms = ["AI", "blockchain", "cloud", "quantum"]
    series = {t: {} for t in terms}
    for r in placebo:
        if r["term"] in series:
            series[r["term"]][int(r["year"])] = float(r["marketing_pct"])
    yrs = sorted(series["AI"])
    styles = {  # AI bold and hot; controls muted
        "AI":         dict(color=MARKET, lw=2.8, label='"AI-powered" / "AI-driven"'),
        "blockchain": dict(color="#6a8caf", lw=1.6, label='"blockchain-…"'),
        "cloud":      dict(color=MUTED, lw=1.6, label='"cloud-…"'),
        "quantum":    dict(color="#b0a58f", lw=1.6, label='"quantum-…"'),
    }
    fig, ax = plt.subplots(figsize=(8, 4.6))
    for t in terms:
        ax.plot(yrs, [series[t][y] for y in yrs], **styles[t])
    ai_last = series["AI"][yrs[-1]]
    ax.set_ylim(0, ai_last * 1.15)
    ax.annotate(f"{ai_last:.1f}%", (yrs[-1], ai_last), textcoords="offset points",
                xytext=(-42, -2), fontsize=10, color=MARKET, fontweight="bold")
    ctrl_max = max(series[t][yrs[-1]] for t in terms if t != "AI")
    ax.text(0.02, 0.60, f"blockchain, cloud, quantum:\nall below {ctrl_max:.1f}% in {yrs[-1]}",
            transform=ax.transAxes, fontsize=9, color=INK)
    ax.legend(frameon=False, fontsize=9, loc="upper left")
    _style(ax, "Only AI got the marketing treatment",
           'Share of 10-K filers using the "<term>-powered" / "<term>-driven" form, same template for every term',
           "% of 10-K filers")
    _save(fig, "f5_placebo")


def fig6_extraction(screen):
    # The capital-extraction instrument spreading through filings: the pre-funded warrant,
    # the ownership blocker, and the paired structure that routes dilution around Section 16.
    # Reads the engine's long-format output (screen_registry.csv); the sec16_evasion surface
    # is the single source of truth for these three sub-signals.
    def series(signal_id):
        d = {int(r["year"]): float(r["pct"]) for r in screen if r["signal_id"] == signal_id}
        return d
    pfw_d = series("sec16_evasion.prefunded_warrant")
    blk_d = series("sec16_evasion.ownership_blocker")
    both_d = series("sec16_evasion.paired")
    yrs = sorted(pfw_d)
    pfw = [pfw_d[y] for y in yrs]
    blk = [blk_d.get(y, 0.0) for y in yrs]
    both = [both_d.get(y, 0.0) for y in yrs]
    fig, ax = plt.subplots(figsize=(8, 4.6))
    ax.plot(yrs, pfw, color="#6a8caf", lw=2.0, label='"pre-funded warrant"')
    ax.plot(yrs, blk, color=MUTED, lw=2.0, label='"beneficial ownership limitation" (blocker)')
    ax.plot(yrs, both, color=MARKET, lw=2.8, label="both in the same filing (Section 16 evasion)")
    ax.fill_between(yrs, both, color=MARKET, alpha=0.07)
    ax.set_ylim(0, max(pfw) * 1.15)
    ax.annotate(f"{pfw[-1]:.1f}%", (yrs[-1], pfw[-1]), textcoords="offset points",
                xytext=(-40, 2), fontsize=9, color="#6a8caf", fontweight="bold")
    ax.annotate(f"{both[-1]:.1f}%", (yrs[-1], both[-1]), textcoords="offset points",
                xytext=(-34, -4), fontsize=9, color=MARKET, fontweight="bold")
    ax.legend(frameon=False, fontsize=8.5, loc="upper left")
    _style(ax, "The extraction instrument spread through filings",
           "Share of 10-K filers disclosing the pre-funded-warrant / ownership-blocker structure "
           "that routes dilution around Section 16",
           "% of 10-K filers")
    _save(fig, "f6_extraction")


def fig7_validation(vsum, vlift):
    # Does the screen predict harm? The forward validation: auditor-distress score measured
    # through fiscal 2021, outcome = an SEC 12(j) delinquent-filer proceeding or trading
    # suspension in 2022+. Reads only the exported aggregate statistics; every issuer-level
    # input stays in the private project.
    fwd = next(r for r in vsum if r["label"] == "failure")
    deciles = [int(r["decile"]) for r in vlift if r["label"] == "failure"]
    rates = [float(r["bad_rate_pct"]) for r in vlift if r["label"] == "failure"]
    fig, ax = plt.subplots(figsize=(8, 4.6))
    colors = [MARKET if r >= 5.0 else ADOPT for r in rates]
    ax.bar(deciles, rates, color=colors, width=0.72)
    for d, r in zip(deciles, rates):
        if r > 0:
            ax.annotate(f"{r:.1f}", (d, r), textcoords="offset points", xytext=(0, 3),
                        ha="center", fontsize=8, color=INK)
    ax.annotate("deciles 1-2: 0.0%", (1.5, 0.35), ha="center", fontsize=9, color=MUTED)
    base = float(fwd["base_rate_pct"])
    ax.axhline(base, color=MUTED, lw=1.0, ls="--")
    ax.annotate(f"base rate {base:.1f}%", (0.62, base + 0.15), fontsize=8, color=MUTED)
    ax.text(0.02, 0.97,
            f"size-adjusted AUC {fwd['auc_score_size_adj']}\n"
            f"95% bootstrap CI ({fwd['ci_lo']}, {fwd['ci_hi']})\n"
            f"n = {int(fwd['n']):,} issuers, {fwd['positives']} failures",
            transform=ax.transAxes, fontsize=9.5, color=INK, va="top",
            bbox=dict(boxstyle="round,pad=0.45", fc="white", ec=GRID))
    ax.set_xticks(deciles)
    ax.set_xlabel("auditor-distress score decile (1 = lowest score, 10 = highest)",
                  fontsize=9, color=INK)
    _style(ax, "The gatekeeper signals predict regulatory failure",
           "Share of issuers hit by an SEC 12(j) proceeding or trading suspension in 2022+, "
           "by pre-2022 auditor-distress score decile",
           "% failing in 2022+")
    _save(fig, "f7_validation",
          source="Source: PCAOB Form AP + SEC enforcement listings + XBRL (aggregates only; "
                 "issuer-level inputs private). Regenerated by pipeline/make_figures.py.")


def fig8_revelation(inc, car):
    """The two legs of the revelation result, side by side.

    LEFT: the screen predicts who will be forced to retract their own financials. The plotted
    series is the STRESSED one — issuers with a prior listing-deficiency notice removed — because
    the unrestricted version is inflated by repeat notices, and the point of the panel is the
    number that survived the restriction rather than the number that looked best.

    RIGHT: what that retraction costs. Mean abnormal return around the filing, with the pre-event
    placebo window shown first. The placebo is the whole argument: no drift before, a drop on the
    day, so the market learned something it did not already know.
    """
    rows = [r for r in inc if r["outcome"] == "y_nonrel" and r["sample"] == "NOPRIOR"
            and r["variant"] == "FULL"]
    rows.sort(key=lambda r: int(r["warning_signs"]))
    signs = [int(r["warning_signs"]) for r in rows]
    rate = [float(r["rate_pct"]) for r in rows]
    nfirm = [int(r["n_firms"]) for r in rows]

    order = ["PLACEBO[-10,-3]", "CAR[0,+1]", "CAR[-1,+1]", "CAR[0,+5]", "CAR[0,+20]"]
    cr = {r["window"]: r for r in car
          if r["event_type"] == "R_NONRELIANCE" and r["window"] in order}
    wins = [w for w in order if w in cr]
    vals = [float(cr[w]["mean_car_pct"]) for w in wins]
    sig = [cr[w]["significant"] == "1" for w in wins]

    fig, (axl, axr) = plt.subplots(1, 2, figsize=(11.6, 5.4))
    fig.subplots_adjust(top=0.70, wspace=0.24, bottom=0.14)

    def _panel(ax, title, subtitle, ylabel):
        """Two-panel variant of _style: the shared helper places its title at y=1.10, which
        collides with a two-line subtitle when panels sit side by side."""
        ax.set_title(subtitle, fontsize=9.5, color=MUTED, loc="left", pad=8)
        ax.text(0.0, 1.20, title, transform=ax.transAxes, fontsize=14.5,
                fontweight="bold", color=INK, va="bottom")
        ax.set_ylabel(ylabel, fontsize=10, color=INK)
        ax.grid(axis="y", color=GRID, linewidth=0.8)
        ax.tick_params(colors=INK, labelsize=9)
        ax.set_axisbelow(True)

    axl.bar([str(s) for s in signs], rate, color=ADOPT, width=0.62)
    for i, (v, n) in enumerate(zip(rate, nfirm)):
        axl.text(i, v + 0.30, f"{v:.1f}%", ha="center", fontsize=10.5,
                 fontweight="bold", color=INK)
        axl.text(i, -1.05, f"n={n:,}", ha="center", fontsize=7.5, color=MUTED)
    _panel(axl, "The screen predicts who retracts",
           "Share later filing 8-K Item 4.02 — financials no\n"
           "longer reliable — within 20 months. Issuers already\n"
           "under a listing-deficiency notice are excluded.", "% of issuers")
    axl.set_xlabel("warning signs in the 10-K", fontsize=10, color=INK)
    axl.set_ylim(-1.8, max(rate) * 1.28)

    cols = [MARKET if s else MUTED for s in sig]
    axr.bar(range(len(wins)), vals, color=cols, width=0.62)
    axr.axhline(0, color=INK, linewidth=0.9)
    lo = min(vals) * 1.45
    for i, (v, s) in enumerate(zip(vals, sig)):
        axr.text(i, v - 0.16, f"{v:+.2f}%", ha="center", va="top", fontsize=9.5,
                 fontweight="bold" if s else "normal", color=INK)
    _panel(axr, "...and what retracting costs",
           "Mean abnormal return vs the Russell 2000,\n"
           "winsorized 1/99. Filled = significant on BOTH\n"
           "the BMP and Corrado rank tests.",
           "% abnormal return")
    axr.set_xticks(range(len(wins)))
    axr.set_xticklabels([w.replace("CAR", "").replace("PLACEBO", "placebo\n") for w in wins],
                        fontsize=8.5)
    axr.set_ylim(lo, 1.15)
    axr.annotate("no drift before the filing:\nthe market did not already know",
                 xy=(0, vals[0] - 0.12), xytext=(0.02, 0.13), textcoords="axes fraction",
                 fontsize=8.5, color=MUTED, ha="left", va="center",
                 arrowprops=dict(arrowstyle="->", color=MUTED, linewidth=0.9,
                                 connectionstyle="arc3,rad=-0.3"))
    _save(fig, "f8_revelation",
          "Source: SEC EDGAR submissions API + full-text search (public); prices via Tiingo. "
          "Aggregates in data/aggregates/.")


def main():
    prev = _read("ai_prevalence.csv")
    buckets = _read("ai_buckets_by_year.csv")
    sector = _read("ai_sector_by_year.csv")
    info = _read("informativeness.csv")
    placebo = _read("placebo_terms.csv")
    screen = _read("screen_registry.csv")
    vsum = _read("validation_summary.csv")
    vlift = _read("validation_lift.csv")
    fig1_adoption(prev)
    fig2_marketing_vs_substance(buckets)
    fig3_sector_diffusion(sector)
    fig4_informativeness(info)
    fig5_placebo(placebo)
    fig6_extraction(screen)
    fig7_validation(vsum, vlift)
    fig8_revelation(_read("revelation_incidence.csv"), _read("car_by_event_type.csv"))
    print("[done] wrote docs/figures/ (f1_adoption, f2_marketing_vs_substance, "
          "f3_sector_diffusion, f4_informativeness, f5_placebo, f6_extraction, "
          "f7_validation, f8_revelation)")


if __name__ == "__main__":
    main()
