#!/usr/bin/env python3
# Usage: python3 pipeline/make_figures.py   # regenerates docs/figures/*.png,*.svg
"""
Render the headline aggregate figures for the README, from committed aggregate
caches only. NO network, NO SEC calls, NO issuer-level data — it reads only the
per-year aggregate CSVs under data/aggregates/ (which the pre-commit gate,
scripts/check_public_safe.py, verifies are issuer-free).

Inputs (all aggregate, one row per year / per year-sector):
  data/aggregates/ai_prevalence.csv     year, pct_artificial_intelligence, pct_generative_ai, ...
  data/aggregates/ai_buckets_by_year.csv year, B_marketing, C_substance, A_core, ...  (% of filers)
  data/aggregates/ai_sector_by_year.csv  year, sic2, pct_of_ai_filings, ...            (long form)

Outputs (committed, embedded in the README):
  docs/figures/f1_adoption.{png,svg}     the label went everywhere
  docs/figures/f2_marketing_vs_substance.{png,svg}   ...but the substance did not follow
  docs/figures/f3_sector_diffusion.{png,svg}         ...and it left software

Reproducible: matplotlib is pinned in requirements.txt; output is stable across
runs (fixed backend/font, suppressed timestamps). Reproducibility is "renders
without error and matches the committed numbers," not a byte-identical diff.
"""
import csv
import os
import sys

import matplotlib
matplotlib.use("Agg")  # headless, deterministic backend
import matplotlib.pyplot as plt

# Deterministic-ish output: stable SVG element ids, matplotlib's always-present
# default font, no interactive state.
matplotlib.rcParams["svg.hashsalt"] = "ai-disclosure-measurement"
matplotlib.rcParams["font.family"] = "DejaVu Sans"
matplotlib.rcParams["figure.dpi"] = 120
matplotlib.rcParams["axes.spines.top"] = False
matplotlib.rcParams["axes.spines.right"] = False

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
AGG = os.path.join(ROOT, "data", "aggregates")
OUT = os.path.join(ROOT, "docs", "figures")

INK = "#1a1a1a"
MUTED = "#8a8a8a"
ADOPT = "#0b6e99"    # adoption / core
MARKET = "#c1440e"   # marketing (hot)
SUBST = "#2f7d4f"    # substance (cool)
GRID = "#e6e6e6"
SOURCE = "Source: SEC EDGAR full-text search + full-index (public). Regenerated by pipeline/make_figures.py."


def _read(name):
    path = os.path.join(AGG, name)
    if not os.path.isfile(path):
        sys.exit(
            "missing aggregate: %s\n"
            "Generate it offline (see pipeline/) and copy it into data/aggregates/."
            % os.path.relpath(path, ROOT)
        )
    with open(path, newline="", encoding="utf-8") as fh:
        return list(csv.DictReader(fh))


def _style(ax, title, subtitle, ylabel):
    ax.set_title(subtitle, fontsize=11, color=MUTED, loc="left", pad=6)
    ax.text(0.0, 1.10, title, transform=ax.transAxes, fontsize=15,
            fontweight="bold", color=INK, va="bottom")
    ax.set_ylabel(ylabel, fontsize=10, color=INK)
    ax.grid(axis="y", color=GRID, linewidth=0.8)
    ax.tick_params(colors=INK, labelsize=9)
    ax.set_axisbelow(True)


def _save(fig, stem):
    os.makedirs(OUT, exist_ok=True)
    fig.text(0.01, 0.005, SOURCE, fontsize=6.5, color=MUTED, ha="left", va="bottom")
    for ext in ("png", "svg"):
        fig.savefig(os.path.join(OUT, f"{stem}.{ext}"),
                    bbox_inches="tight", metadata={"Date": None} if ext == "svg" else {})
    plt.close(fig)
    print(f"[fig] docs/figures/{stem}.png / .svg")


def fig1_adoption(prev):
    yrs = [int(r["year"]) for r in prev]
    ai = [float(r["pct_artificial_intelligence"]) for r in prev]
    gen = [float(r.get("pct_generative_ai", 0) or 0) for r in prev]
    fig, ax = plt.subplots(figsize=(8, 4.6))
    ax.plot(yrs, ai, color=ADOPT, linewidth=2.6, label='"artificial intelligence"')
    ax.plot(yrs, gen, color=MARKET, linewidth=1.8, linestyle="--", label='"generative AI"')
    ax.fill_between(yrs, ai, color=ADOPT, alpha=0.06)
    ax.set_ylim(0, max(ai) * 1.12)
    ax.annotate(f"{ai[0]:.1f}%  ({yrs[0]})", (yrs[0], ai[0]), textcoords="offset points",
                xytext=(6, 8), fontsize=9, color=INK)
    ax.annotate(f"{ai[-1]:.0f}%  ({yrs[-1]})", (yrs[-1], ai[-1]), textcoords="offset points",
                xytext=(-52, -4), fontsize=9, color=INK, fontweight="bold")
    ax.legend(frameon=False, fontsize=9, loc="upper left")
    _style(ax, "The AI label went everywhere",
           'Share of 10-K filers mentioning the phrase, %s–%s' % (yrs[0], yrs[-1]),
           "% of 10-K filers")
    _save(fig, "f1_adoption")


def fig2_marketing_vs_substance(buckets):
    yrs = [int(r["year"]) for r in buckets]
    mkt = [float(r["B_marketing"]) for r in buckets]
    sub = [float(r["C_substance"]) for r in buckets]
    fig, ax = plt.subplots(figsize=(8, 4.6))
    ax.plot(yrs, mkt, color=MARKET, linewidth=2.6, label="Marketing vocabulary  (AI-powered, AI-driven)")
    ax.plot(yrs, sub, color=SUBST, linewidth=2.6, label="Build vocabulary  (LLM, training compute, fine-tuning)")
    ax.fill_between(yrs, mkt, sub, where=[m >= s for m, s in zip(mkt, sub)],
                    color=MARKET, alpha=0.07)
    ax.set_ylim(0, max(mkt) * 1.2)
    ax.annotate(f"{mkt[-1]:.1f}%", (yrs[-1], mkt[-1]), textcoords="offset points",
                xytext=(-38, 4), fontsize=9, color=MARKET, fontweight="bold")
    ax.annotate(f"{sub[-1]:.1f}%", (yrs[-1], sub[-1]), textcoords="offset points",
                xytext=(-30, -12), fontsize=9, color=SUBST, fontweight="bold")
    ax.legend(frameon=False, fontsize=9, loc="upper left")
    _style(ax, "...but the substance did not follow",
           "Cheap marketing language spread; costly build language stayed pinned near zero",
           "% of 10-K filers")
    _save(fig, "f2_marketing_vs_substance")


def fig3_sector_diffusion(sector):
    # SIC-73 (business & IT services / software) share of AI-mention volume, per year.
    share = {}
    for r in sector:
        if str(r["sic2"]).zfill(2) == "73":
            share[int(r["year"])] = float(r["pct_of_ai_filings"])
    yrs = sorted(share)
    vals = [share[y] for y in yrs]
    peak_y = max(yrs, key=lambda y: share[y])
    peak_v = share[peak_y]
    fig, ax = plt.subplots(figsize=(8, 4.6))
    ax.plot(yrs, vals, color=ADOPT, linewidth=2.6)
    ax.fill_between(yrs, vals, color=ADOPT, alpha=0.06)
    ax.set_ylim(0, peak_v * 1.18)
    # Honest annotation: the series rises (noisy, small early samples) and then
    # falls from its ~2018 peak. Mark the peak and the latest year, not 2001.
    ax.annotate(f"peak {peak_v:.0f}% ({peak_y})", (peak_y, peak_v),
                textcoords="offset points", xytext=(-20, 8), fontsize=9,
                color=INK, fontweight="bold")
    ax.annotate(f"{vals[-1]:.0f}% ({yrs[-1]})", (yrs[-1], vals[-1]),
                textcoords="offset points", xytext=(-30, -14), fontsize=9,
                color=INK, fontweight="bold")
    _style(ax, "...and it spread beyond software",
           "Software's (SIC-73) share of all AI mentions: after its ~%s peak, the label diffuses into every sector" % peak_y,
           "SIC-73 share of AI mentions, %")
    _save(fig, "f3_sector_diffusion")


def main():
    prev = _read("ai_prevalence.csv")
    buckets = _read("ai_buckets_by_year.csv")
    sector = _read("ai_sector_by_year.csv")
    fig1_adoption(prev)
    fig2_marketing_vs_substance(buckets)
    fig3_sector_diffusion(sector)
    print("[done] wrote docs/figures/ (f1_adoption, f2_marketing_vs_substance, f3_sector_diffusion)")


if __name__ == "__main__":
    main()
